apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: lockcd
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "lockcd.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "lockcd.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "lockcd.selectorLabels" . | nindent 8 }}
    spec:
      hostPID: true
      containers:
      - name: lockcd
        image: "{{ .Values.lockcd.image.repository }}:{{ .Values.lockcd.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.lockcd.image.pullPolicy }}
        securityContext:
          privileged: true
        env:
        - name: LOCKC_CHECK_LSM_SKIP
          value: "1"
{{- if .Values.lockcd.debug.enabled }}
        - name: LOCKC_DEBUG
          value: "1"
{{- end }}
        volumeMounts:
{{- if .Values.lockcd.config.enabled }}
        - mountPath: /etc/lockc
          name: lockc-config
{{- end }}
        - name: bpffs
          mountPath: /sys/fs/bpf
        - name: usr
          mountPath: /host/usr
        - name: run
          mountPath: /host/run
      serviceAccountName: {{ include "lockc.serviceAccountName" . }}
      tolerations:
      - operator: Exists
      volumes:
{{- if .Values.lockcd.config.enabled }}
      - configMap:
          name: {{ .Values.lockcd.config.name }}
        name: lockc-config
{{- end }}
      - name: bpffs
        hostPath:
          path: /sys/fs/bpf
          type: Directory
      - name: usr
        hostPath:
          path: /usr
          type: Directory
      - name: run
        hostPath:
          path: /run
          type: Directory
