apiVersion: v2
name: lockc
version: 0.1.6
description: A Helm chart for Kubernetes lockc agent and daemon
type: application
icon: https://raw.githubusercontent.com/lockc-project/assets/main/icon-lockc.svg
home: https://lockc-project.github.io/book/
appVersion: "v0.1.6"
maintainers:
  - name: Michal Rostecki
    email: vadorovsky@gmail.com
  - name: Michal Jura
    email: mjura@suse.com
